language: csharp
solution: PleaseBehave.sln
install:
  - nuget restore PleaseBehave.sln
  - nuget install xunit.runner.console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release PleaseBehave.sln
  - mono ./testrunner/xunit.runner.console.2.1.0-beta2-build2981/tools/xunit.console.exe ./PleaseBehaveTests/bin/Release/PleaseBehaveTests.dll
